name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci_test: # <--- Ini adalah `id` job yang menentukan nama status check di branch protection
    name: CI / test # <--- Ini cuma nama tampilan di PR, tidak berpengaruh ke branch protection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
